file_format: "1"
id: swept
name: Swept
type: shield
url: https://github.com/toomanyls/zmk-config-swept
requires: [pro_micro]
features:
  - keys
  - pointer
siblings:
  - swept_left
  - swept_right
  - swept_dongle
